;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        centaur-tabs-backward-tab
        comment-or-uncomment-region
        counsel-M-x
        indent-for-tab-command
        markdown-outdent-or-delete
        sh-assignment
        swiper
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-paren
        counsel-find-file
        counsel-recentf
        delete-window
        ))
