;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-command-master
        TeX-insert-backslash
        ace-jump-mode
        beginning-of-visual-line
        c-electric-brace
        c-electric-lt-gt
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        cua--prefix-override-handler
        cua-exchange-point-and-mark
        forward-sentence
        ido-find-file
        ignore
        indent-for-tab-command
        kmacro-end-or-call-macro
        mouse-set-region
        org-self-insert-command
        py-electric-colon
        py-electric-comment
        py-indent-or-complete
        shk-tabbar-next
        shk-tabbar-prev
        smex
        tabbar-backward-group
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        ace-mc-add-char
        ace-mc-add-multiple-cursors
        ace-mc-add-single-cursor
        ace-mc-do-keyboard-reset
        c-electric-colon
        comment-or-uncomment-region
        cua-paste
        end-of-buffer
        end-of-visual-line
        ido-write-file
        isearch-yank-kill
        mark-whole-buffer
        overwrite-mode
        previous-buffer
        py-electric-delete
        scroll-other-window
        sh-assignment
        tabbar-select-tab-callback
        ))
