(deftheme zenburnMod
  "Created 2017-07-07.")

(custom-theme-set-variables
 'zenburnMod
 '(fci-rule-color "#383838"))

(custom-theme-set-faces
 'zenburnMod
 '(button ((t (:underline t))))
 '(link ((t (:foreground "#F0DFAF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#D0BF8F" :underline t :weight normal))))
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(escape-glyph ((t (:foreground "#F0DFAF" :bold t))))
 '(fringe ((t (:background "#000000" :foreground "#000000"))))
 '(header-line ((t (:box nil))))
 '(highlight ((t (:background "#383838"))))
 '(success ((t (:foreground "#7F9F7F" :weight bold))))
 '(warning ((t (:foreground "#DFAF8F" :weight bold))))
 '(tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(completions-annotations ((t (:foreground "#656555"))))
 '(match ((t (:background "#2B2B2B" :foreground "#DFAF8F" :weight bold))))
 '(isearch ((t (:foreground "#D0BF8F" :weight bold :background "#5F5F5F"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#8C5353"))))
 '(lazy-highlight ((t (:foreground "#D0BF8F" :weight bold :background "#383838"))))
 '(menu ((t (:foreground "#DCDCCC" :background "#3F3F3F"))))
 '(minibuffer-prompt ((t (:foreground "#F0DFAF"))))
 '(mode-line ((t (:box nil))))
 '(mode-line-buffer-id ((t (:foreground "#F0DFAF" :weight bold))))
 '(mode-line-inactive ((t (:foreground "#F0DFAF" :box nil))))
 '(region ((t (:background "#7f5f7f"))))
 '(secondary-selection ((t (:background "#5F5F5F"))))
 '(trailing-whitespace ((t (:background "#CC9393"))))
 '(vertical-border ((t (:foreground "#DCDCCC"))))
 '(font-lock-builtin-face ((t (:foreground "#DCDCCC" :weight bold))))
 '(font-lock-comment-face ((t (:foreground "#7F9F7F"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5F7F5F"))))
 '(font-lock-constant-face ((t (:foreground "#BFEBBF"))))
 '(font-lock-doc-face ((t (:foreground "#9FC59F"))))
 '(font-lock-function-name-face ((t (:foreground "#93E0E3"))))
 '(font-lock-keyword-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#94BFF3"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#F0DFAF" :weight bold))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#7F9F7F" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#CC9393"))))
 '(font-lock-type-face ((t (:foreground "#7CB8BB"))))
 '(font-lock-variable-name-face ((t (:foreground "#DFAF8F"))))
 '(font-lock-warning-face ((t (:foreground "#D0BF8F" :weight bold))))
 '(ido-first-match ((t (:foreground "#94BFF3" :weight bold))))
 '(ido-only-match ((t (:foreground "#DFAF8F" :weight bold))))
 '(ido-subdir ((t (:foreground "#F0DFAF"))))
 '(ido-indicator ((t (:foreground "#F0DFAF" :background "#8C5353"))))
 '(linum ((t (:background "#000000" :foreground "#335da5"))))
 '(show-paren-mismatch ((t (:foreground "#DCA3A3" :background "#6F6F6F" :weight bold))))
 '(show-paren-match ((t (:background "#6F6F6F" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((t (:foreground "#FFFFEF" :weight bold))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#BC8383" :weight bold))))
 '(undo-tree-visualizer-default-face ((t (:foreground "#DCDCCC"))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#F0DFAF"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#93E0E3"))))
 '(linum-highlight-face ((t (:inherit default :background "black" :foreground "#77d1fd"))))
 '(default ((t (:background "#000000" :foreground "#DCDCCC")))))

(provide-theme 'zenburnMod)
